Ignore Early Hints (4.9.x)
square/okhttp pull request #7479
Opened 2022-10-17 07:34 UTC by yschimke

(cherry picked from commit b565eecf167918253145bce2c348b0bb0ef58b0c)

2022-10-17 07:35 UTC, yschimke commented
@swankjesse CallTest can't be reused because of addInformationResponse which was added in 5

2022-11-04 10:36 UTC, reschke requested changes

2022-11-04 10:36 UTC, reschke commented on okhttp/src/main/kotlin/okhttp3/internal/http/CallServerInterceptor.kt
> +  private fun shouldIgnoreAndWaitForRealResponse(code: Int, exchange: Exchange): Boolean = when {
That seems to do the wrong thing for all 1xx codes except 100 and 103.

2022-11-04 11:34 UTC, yschimke commented
The intent was to get something in quick to fix an obviously surfaced bug affecting cloudflare customers.

Then a bigger fix in https://github.com/square/okhttp/issues/2257

It's in the blocker list for 5, https://github.com/square/okhttp/issues/7366

Is there a simple fix here we can make to expand it to all other codes including future 1xx and codes we aren't expecting?

2022-11-04 11:35 UTC, reschke commented
Just treat all 1xx the same, except for the one that is somewhat special (101).

2022-11-04 12:06 UTC, yschimke commented
I'll close this, make a minor update for 5.x/main.  Then backport.

2022-11-04 12:06 UTC, closed without merging